name: "Youtube stats"
description: An  adapter that gets youtube stats.
node_identifier: youtube_cl_ea
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: Youtube
    url: https://youtube.com
parameters:
  - part
  - tag